### ISSUE TITLE
Book a room out option in the presence of a partially booked room.

### ISSUE THREAD

**Issue by tommytran0** [FibreKitty/FuzzyLogic-Web#10]
if a room already has slots booked in it, the book a room option is still available for that slot for future bookings. Furthermore, the second booker booking out the room is charged for "8 - (their party #)"  even though there are slots already booked.

Example:
Person 1 books Casino monday 4:40 for 2 people. get charged $56 

Person 2 tries to book same slot and chooses "1 person" and books the room out. They are charged $28 + $147 for 7 slots.

**Comment by FibreKitty** [comment]
Fixed; book out can only be checked if room is completely empty.

**Comment by tommytran0** [comment]
This bug is still present when I tested it just now. I booked 3 slots in Casino on Monday at 5:55PM. Then I go back and try to book it with a party of one and choose the book out option.

**Comment by FibreKitty** [comment]
Clear the browser's cache, refresh the page and try again

**Comment by tommytran0** [comment]
Confirmed fixed. thank you
